<!-- Generated by documentation.js. Update this documentation by updating the source code. -->

## BypassNode

**Extends AudioNode**

### Parameters

*   `context` **BaseAudioContext**&#x20;
*   `options` **[Object][1]**  (optional, default `{}`)

    *   `options.active` **[boolean][2]**  (optional, default `false`)

### subGraphInput

Node to connect to the input of the sub graph

Type: GainNode

#### Examples

```javascript
const bypass = new Bypass(audioContext, { active: false });
const filter = new BiquadFilterNode(audioContext);
bypass.subGraphInput.connect(filter).connect(bypass.subGraphOutput);
```

### subGraphOutput

Node to connect to the input of the sub graph

Type: GainNode

#### Examples

```javascript
const bypass = new Bypass(audioContext, { active: false });
const filter = new BiquadFilterNode(audioContext);
bypass.subGraphInput.connect(filter).connect(bypass.subGraphOutput);
```

### active

Defines if the Bypass is active, i.e. if true the signal doesn't pass through
the sub graph and flows directly to the output.

Type: [boolean][2]

### setActiveAtTime

Activate or deactivate the `BypassNode` at given time.

#### Parameters

*   `active` **[boolean][2]** whether the bypass is active or not
*   `when` **[number][3]** time at which the change should be applied. In audio
    context current time coordinates

## CollectorNode

**Extends AudioNode**

### Parameters

*   `context` **BaseAudioContext**&#x20;
*   `options` **[Object][1]**  (optional, default `{}`)

    *   `options.ratio` **[boolean][2]** Initial ratio (optional, default `0`)
    *   `options.curve` **[Array][4]<[number][3]>** Curve to apply for the transition.
        Defaults to equal power curve. (optional, default `null`)

### inputs

An array of length 2, containing the 2 inputs of the CollectorNode.

Type: [Array][4]\<GainNode>

### ratio

An AudioParam that controls the amount of incoming signal from the inputs to be routed to the output:

*   `inputs[0]` is at maximum volume when ratio is set to `0`
*   `inputs[1]` is at maximum volume when ratio is set to `1`

Type: AudioParam

## DistributorNode

**Extends AudioNode**

### Parameters

*   `context` **BaseAudioContext**&#x20;
*   `options` **[Object][1]**  (optional, default `{}`)

    *   `options.ratio` **[boolean][2]** Initial ratio (optional, default `0`)
    *   `options.curve` **[Array][4]<[number][3]>** Curve to apply for the transition.
        Defaults to equal power curve. (optional, default `null`)

### ratio

An AudioParam that controls the amount of incoming signal to route between the two outputs:

*   a ratio of 0 is routed to output 0
*   a ratio of 1 is routed to output 1

Type: AudioParam

## MuteNode

**Extends AudioNode**

### Parameters

*   `context` **BaseAudioContext**&#x20;
*   `options` **[Object][1]**  (optional, default `{}`)

    *   `options.active` **[boolean][2]**  (optional, default `false`)

### active

Defines whether the mute is active (muted) or not (pass trough).

Type: [boolean][2]

### setActiveAtTime

Activate or deactivate the `MuteNode` at given time.

#### Parameters

*   `active` **[boolean][2]** Whether the bypass is active or not.
*   `when` **[number][3]** Time at which the change should be applied. In audio
    context current time coordinates.

## stages

Number of cascading allpass filters.

Note that changing this parameter at runtime may cause discontinuities

Type: [Number][3]

## ratio

Mix ratio between dry signal (0) and wet signal (1)

## rate

Rate (in Hz) of the LFO modulating the frequency of the filter bank.

## depth

Depth (in Hz) of the modulation applied to the frequency of the filter bank by the LFO.

A depth of 100 applied to a frequency of 1000 will produce a frequency comprised
between 900 and 1100.

## frequency

Frequency of the all pass filters of the filter bank. This is the frequency at
which the phases will be shifted.

## PlaceholderNode

**Extends AudioNode**

### Parameters

*   `context` **BaseAudioContext**&#x20;
*   `options` **[Object][1]**  (optional, default `{}`)

    *   `options.node` **AudioNode**  (optional, default `null`)

### node

Wrapped AudioNode

Type: AudioNode

### setNodeAtTime

Replace the wrapped AudioNode at given time.

<i>Note that using this method in an wrong order according to the timeline will result in undefined behavior, e.g.:</i>

```js
wrapper.setNodeAtTime(node1, audioContext.currentTime + 2);
wrapper.setNodeAtTime(node2, audioContext.currentTime + 1);
```

#### Parameters

*   `node` **AudioNode** AudioNode to be wrapped.
*   `when` **[number][3]** Time at which the change should be applied. In audio
    context current time coordinates.

## VolumeNode

**Extends AudioNode**

### Parameters

*   `context` **BaseAudioContext**&#x20;
*   `options` **[Object][1]**  (optional, default `{}`)

    *   `options.volume` **[number][3]**  (optional, default `0`)
    *   `options.min` **[number][3]**  (optional, default `-80`)
    *   `options.max` **[number][3]**  (optional, default `12`)
    *   `options.controlCurve`   (optional, default `null`)

### min

Minimum value of the volume in dB.

Type: [number][3]

### max

Maximum value of the volume in dB.

Type: [number][3]

### volume

An AudioParam that Represents the amount of gain in decibels to apply.

Type: AudioParam

[1]: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object

[2]: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Boolean

[3]: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Number

[4]: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array
