<!-- Generated by documentation.js. Update this documentation by updating the source code. -->

## PlaceholderNode

**Extends AudioNode**

### Parameters

*   `context` **BaseAudioContext**&#x20;
*   `options` **[Object][1]**  (optional, default `{}`)

    *   `options.node` **AudioNode**  (optional, default `null`)

### node

Wrapped AudioNode

Type: AudioNode

### setNodeAtTime

Replace the wrapped AudioNode at given time.

<i>Note that using this method in an wrong order according to the timeline will result in undefined behavior, e.g.:</i>

```js
wrapper.setNodeAtTime(node1, audioContext.currentTime + 2);
wrapper.setNodeAtTime(node2, audioContext.currentTime + 1);
```

#### Parameters

*   `node` **AudioNode** AudioNode to be wrapped.
*   `when` **[number][2]** Time at which the change should be applied. In audio
    context current time coordinates.

[1]: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object

[2]: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Number
