<!-- Generated by documentation.js. Update this documentation by updating the source code. -->

## VolumeNode

**Extends AudioNode**

### Parameters

*   `context` **BaseAudioContext**&#x20;
*   `options` **[Object][1]**  (optional, default `{}`)

    *   `options.volume` **[number][2]**  (optional, default `0`)
    *   `options.min` **[number][2]**  (optional, default `-80`)
    *   `options.max` **[number][2]**  (optional, default `12`)
    *   `options.curve` **[number][2]**  (optional, default `null`)

### Examples

```javascript
import {
  AudioContext,
  AudioBufferSourceNode,
} from 'isomorphic-web-audio-api';
import {
  AudioBufferLoader,
  VolumeNode,
} from '@ircam/sc-audio';

// in browsers, you will need to resume on a user gesture
const audioContext = new AudioContext();
// load an audio buffer
const loader = new AudioBufferLoader(audioContext);
const buffer = await loader.load('../assets/drum-loop.wav');

// build graph and start source
const fader = new VolumeNode(audioContext);
const src = new AudioBufferSourceNode(audioContext, { buffer, loop: true });
src.connect(fader).connect(audioContext.destination);

// start source and ramp from -60 to 0 dB
const now = audioContext.currentTime;
src.start(now);
fader.volume.setValueAtTime(-60, now);
fader.volume.linearRampToValueAtTime(0, now + buffer.duration);
```

### min

Minimum value of the volume in dB.

Type: [number][2]

### max

Maximum value of the volume in dB.

Type: [number][2]

### curve

Curve used to map from db to linear gain.

Note that the returned sequence value is a copy of the actual curve used, then
modifying the returned value won't affect the audio computation.

Type: [Float32Array][3]

### volume

An AudioParam that Represents the amount of gain in decibels to apply.

Type: AudioParam

[1]: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object

[2]: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Number

[3]: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Float32Array
